baseurl = "http://joshuamrosenberg.com"
languageCode = "en-us"
title = "Joshua M. Rosenberg, Ph.D."
theme = "hugo-xmin"
googleAnalytics = "UA-43032207-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
paginate = 10
math = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Research Group Website"
    url = "https://makingdatasciencecount.com"
    weight = 4

[params]
    description = "Joshua M. Rosenberg's Homepage"
    footer = "&copy; [Joshua M. Rosenberg](https://joshuamrosenberg.com) 2015 -- 2019 | [Google Scholar](https://scholar.google.com/citations?user=nxVowRQAAAAJ&hl=en) | [GitHub](https://github.com/jrosen48) | [ORCID](http://orcid.org/0000-0003-2170-0447) | [OSF](https://osf.io/xzqbc/)"
