baseURL = "https://jrosen48.github.io/utk-homepage"
languageCode = "en-us"
title = "Joshua M. Rosenberg, Ph.D. - Archive"
theme = "hugo-xmin"
# Removed Google Analytics for archive version
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
math = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Vita"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 5

[params]
    description = "Joshua M. Rosenberg's Homepage"
    footer = "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) | [Google Scholar](https://scholar.google.com/citations?user=nxVowRQAAAAJ&hl=en) | [GitHub](https://github.com/jrosen48) | [ORCID](http://orcid.org/0000-0003-2170-0447) | [OSF](https://osf.io/xzqbc/)"
