baseurl = "http://joshuamrosenberg.com"
languageCode = "en-us"
title = "Joshua M. Rosenberg, Ph.D."
theme = "hugo-xmin"
googleAnalytics = "UA-43032207-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
math = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Substack"
    url = "https://joshuamrosenberg.substack.com"
    weight = 4
[[menu.main]]
    name = "Research Group"
    url = "https://makingdatasciencecount.com"
    weight = 5

[params]
    description = "Joshua M. Rosenberg's Homepage"
    footer = "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) | [Google Scholar](https://scholar.google.com/citations?user=nxVowRQAAAAJ&hl=en) | [GitHub](https://github.com/jrosen48) | [ORCID](http://orcid.org/0000-0003-2170-0447) | [OSF](https://osf.io/xzqbc/)"
