---
title: 'Two data packages: Rail-trails and an assessment of student achievement'
author: ~
date: '2017-10-25'
slug: two-open-datasets-rail-trails-and-an-assessment-of-student-achievement
categories: [r]
tags: [open-science]
description: Desc
meta_img: /images/image.jpg
---

Because of interest and the need for better examples (for teaching and for use in tools under-development), such as [prcr](https://github.com/jrosen48/prcr) and [tidyLPA](https://github.com/jrosen48/tidyLPA), I worked to create two data packages, data easily available through an R package. 

A benefit of the data being in an `R` package is that it is even easier to access than other formats (in `R`): Just load the name of the package and type the name of the data frame, or, if the data is included as built-in data in another package (one that is loaded), just type the name of the data frame. This can be helpful because data packages can make it easy to use an interesting dataset right away (loading data can sometimes be surprisingly hard) Another benefit is the data are documented and easily joined (in the case of the student questionnaire and achievement data in the PISA data) with related information, such as students' schools. The data are also saved in an efficient format.

* [pisaUSA15](https://github.com/jrosen48/pisaUSA15): Data package that provides student questionnaire data from the 2015 PISA for students in the United States of America. I've used these for examples in the `prcr` and `tidyLPA` packages. More information is available at http://www.oecd.org/pisa/data/.

* [railtrails](https://github.com/jrosen48/railtrails): Data package with trail data from the Rails-to-Trails Conservancy, including the trail name, state, distance, and surface. I've used this data to illustrate ideas behind mixed effects (or multi-level) models [here](https://jrosen48.github.io/blog/characteristics-of-rail-trails/), [here](https://jrosen48.github.io/blog/comparing-mixed-effects-and-linear-models/), and [here](https://jrosen48.github.io/blog/michigan-rail-trails-and-pathways-through-data/). More information is available at https://www.traillink.com/. UPDATE: This package is now available on CRAN (see [here](https://cran.r-project.org/web/packages/railtrails/index.html)).