---
title: "A few podcasts I always listen to"
author: Joshua Rosenberg
date: '2017-09-05'
description: Desc
meta_img: /images/image.jpg
slug: podcasts-i-do-not-miss
categories: [personal]
tags: [podcasts]
---

Between commuting by bicycle and working, I listen to a lot of podcasts. I listen to podcasts to learn something new, keep up with the news, and, occasionally, hear other viewpoints. I thought it would be worth sharing a few that I (almost) never miss downloading and listening to, especially those that others may not regularly hear about, are new, or are sort of niche in terms of the audience. For what it's worth, I use [Pocket Casts](https://www.shiftyjelly.com/pocketcasts) both on my computer and phone, as it syncs easily between them and has an easy to use interface. 

### Podcasts I always listen to (in no particular order)

- [The Pollsters](https://www.google.com/search?q=the+pollsters&oq=the+pollsters&aqs=chrome..69i57j69i64.1703j0j7&sourceid=chrome&ie=UTF-8)

Kristen (a Republican-leaning pollster) and Margie (a Democrat-leaning pollster) talk. It's not just about politics and I always learn something new, whether about public opinion or polling methodology. 

- [The Daily](https://www.nytimes.com/podcasts/the-daily?mcubz=3&_r=0)

A story every day. Sort of new, I listen to it every day.

- [It's Been a Minute with Sam Sanders](http://www.npr.org/podcasts/510317/its-been-a-minute-with-sam-sanders)

Sam Sanders was part of the NPR Politics podcast I listened to all last year; his new show is great, and is not just about politics. If there is absolutely **one** I never miss, this has become it. 

- [FiveThirtyEight Politics Podcast](https://fivethirtyeight.com/tag/politics-podcast/)

Smart, occasionally funny, obviously about politics. 

- [Conversations With Tyler](https://medium.com/conversations-with-tyler)

Interviews between Tyler Cowen and his guest. More of these than I can count have been incredible and worth returning to listen to.

- [The Effort Report](http://effortreport.libsyn.com/)

Elizabeth and Roger are insightful about academia; this is one podcast after which I always feel like I learned something useful, and often end up discussing episodes with friends and colleagues who also listen to it.

- [The Ezra Klein Show](https://www.vox.com/ezra-klein-show-podcast)

Timely, well-researched interviews with a variety of guests, from a more liberal viewpoint.

- [The Editors](https://www.nationalreview.com/media/editors)

This took me a little bit of time to find, but after searching for a conservative podcast, I found that they are reasonable, and while I disagree with many of the conclusions they reach, I can at least understand how they got there.

### Any others?

I listen to a bunch of others (probably too many to reasonably keep up with). The above are those that stood out for one reason or another. Message me [on Twitter](https://twitter.com/jrosenberg6432) if you would like to suggest any.