---
title: Sort-of-Bayesian and Bayesian Reanalyses of Already-Analyzed Data
author: ''
date: '2018-12-30'
slug: sort-of-bayesian-and-bayesian-reanalyses-of-already-analyzed-data
categories:
  - r
  - walkthrough
tags:
  - Bayesian
---



```{r}
library(lme4)
library(brms)
library(readr)

uv_data <- read_csv("static/data/uv-data.csv")

```

```{r}

m0 <- lmer(PostUV_ave ~ Int + PreUV_s + Int+ PreEff_s + PreInt_s + Gender, data = df)

m1 <- lmer(PostUV_ave ~ Int + PreUV_s + Int+ PreEff_s + PreInt_s + Gender + (1|ClassTeacher), data = df)

m1b <- brm(PostUV_ave ~ Int + PreUV_s + Int+ PreEff_s + PreInt_s + Gender + (1|ClassTeacher), data = df)

m1bp <- brm(PostUV_ave ~ Int + PreUV_s + Int+ PreEff_s + PreInt_s + Gender + (1|ClassTeacher), data = df, prior = set_prior("normal(.40, .20)", class = "b", coef = "Int"))

# .49 [0.43, 0.56]
# https://journals.sagepub.com/doi/pdf/10.3102/0034654315617832?casa_token=tADQ9ZcVizoAAAAA%3APNUK7bhjQFAHgfbGJ0bTp3C3dLP0o4BJbCQQHx4pX4XmxRy1g5E8EQv9Xlk54pymuJILPQ4WxxY2-g
```