---
title: Outcomes from a self-generated utility value intervention in science (in IJER)
author: ~
date: '2017-12-30'
slug: new-article-on-a-utility-value-intervention-in-ijer
categories: []
tags: []
description: Desc
meta_img: /images/image.jpg
---

The [Scientific Practices project](http://www.sesp.northwestern.edu/learning-sciences/research-projects/), was focused on engaging middle school students in scientific and engineering practices (such as developing and using models, constructing explanations of phenomena, and analyzing and interpreting data). As part of this longitudinal project, we carried out field experiments to understand the impact of specific features of the curriculum.

In this paper published in the [International Journal of Educational Research](https://www.journals.elsevier.com/international-journal-of-educational-research) with Mete Akcaoglu, John Ranellucci, Christina Schwarz, and I examined whether asking students to generate ideas about how what they were learning about could be useful in the future. 

Students who wrote about why what they were learning was relevant generated future uses for what they were learning. Students who wrote about how what they were learning about could be useful demonstrated higher levels of cognitive processing in their responses, which we found through the use of a computational, Natural Language Processing technique (the [LIWC](http://liwc.wpengine.com/)). We found that these students who wrote about how what they were learning could be useful reported changes in their utility value for science (in comparison to students in a control group who were asked to summarize what they were learning), but not higher levels of interest in science.

Here's the abstract:

> The purpose of this field experiment was to understand whether fifth and sixth-grade students were able to write about the usefulness and relevance of what they were learning in their science class through self-generated reflections and to examine the impacts of this activity on students’ value, utility value, and interest for science. Analysis of students’ essays revealed in the self-generated reflection condition students connected what they were learning to their lives significantly more than the control condition. Linguistically, student essays did not differ between the two conditions, except for cognitive processing. Self-reflecting increased students’ utility value but not value nor interest. Self-efficacy did not moderate these relations. Implications for extending self-generated utility value and broader social-psychological interventions for early adolescent students are discussed.

The paper is available from [here](https://www.sciencedirect.com/science/article/pii/S0883035517308492).