---
title: Rock Climbing in the News (Updated)
author: ~
date: '2017-07-09'
slug: rock-climbing-in-the-news-updated
tags: [r]
description: 'A quick look at how often rock climbing is mentioned after noteworthy events using newsflash'
---

When I was visiting my brother, we came across a neat tool to track mentions of topics in the news, [newsflash](https://github.com/hrbrmstr/newsflash). 

We looked at how mentions of rock climbing spiked after particular media (a special on rock climber Alex Honnold) or events (the first ascent of the Dawn Wall in Yosemite National Park). You can read (a bit) more in [the post](https://jrosen48.github.io/2017/03/11/the-internet-archives-television-news-archive-and-newsflash/), if you'd like.

Anyhow, he messaged me because he was interested in whether there ws a spike in activity after a recent news-worthy event - the [first solo climb of El Capital](http://sanfrancisco.cbslocal.com/2017/06/04/alex-honnold-free-climb-el-capitan/) by Alex Honnold (the same rock climber there was the special that seemed to earlier be associated with an increase in news coverage). 

So, we checked again:

```{r}
library(newsflash)
library(tidyverse)
library(hrbrthemes)

climb <- query_tv("rock climbing", filter_network = "AFFNETALL")

t1 <- lubridate::ymd_hms("2012-05-30 00:00:00", tz = "UTC")
t2 <- lubridate::ymd_hms("2016-01-12 00:00:00", tz = "UTC")
t3 <- lubridate::ymd_hms("2017-07-03 00:00:00", tz = "UTC")

t1i <- lubridate::ymd_hms("2012-04-30 00:00:00", tz = "UTC")
t2i <- lubridate::ymd_hms("2015-12-12 00:00:00", tz = "UTC")
t3i <- lubridate::ymd_hms("2017-06-03 00:00:00", tz = "UTC")

climb$timeline$date_w <- lubridate::round_date(climb$timeline$date_start, unit = "week")

mutate(climb$timeline, date_start=as.Date(date_w)) %>% 
    ggplot(aes(date_start, value)) +
    geom_col() +
    theme(legend.position="bottom") +
    theme(axis.text.x=element_text(hjust=c(0, 0.5, 0.5, 0.5, 0.5, 0.5))) +
    ggtitle("Rock Climbing on Affiliate TV Stations") +
    labs(subtitle = "For ABC, CBS, FOX, NBC, and PBS") +
    ylab("Number of Mentions") +
    
    geom_vline(xintercept = as.numeric(as.Date(t1)), color = "#cd2626", alpha = .4) +
    geom_vline(xintercept = as.numeric(as.Date(t2)), color = "#cd2626", alpha = .4) + 
    geom_vline(xintercept = as.numeric(as.Date(t3)), color = "#cd2626", alpha = .4) + 
    
    annotate("text", x = as.Date(t1i), y = 45, label = "60 Minutes Special on Honnold", angle = 90, family = "Roboto Condensed") +
    annotate("text", x = as.Date(t2i), y = 45, label = "First Ascent of Dawn Wall", angle = 90, family = "Roboto Condensed") +
    annotate("text", x = as.Date(t3i), y = 45, label = "Honnold Free Climbs El Cap", angle = 90, family = "Roboto Condensed") +
    labs(caption = "Data from the Internet Archive and GDELT Television Explorer (http://television.gdeltproject.org/cgi-bin/iatv_ftxtsearch/iatv_ftxtsearch).") +
    theme_ipsum_rc(grid="XY") +
    scale_x_date(date_breaks="6 months",
                 date_labels = "%b %Y") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

The results seems to suggest that this event was hardly covered at all. I wonder if this is due to the type of news networks being searched - affiliate, or local, networks for ABC, CBS, PBS, and so on. I wonder if perhaps it was covered more on national networks (something you can check through newsflash). Or, it could be that it just wasn't covered!

# A bit more

On another date, I looked with my colleague Patrick Beymer at [how often the Common Core State Standards and the Next Generation Science Standards were mentioned](https://jrosen48.github.io/2017/03/16/common-core-and-ngss-are-not-on-the-news/) (they weren't mentioned a lot!).