---
title: New post on engaging students in “data practices” in online science classes (in the MVLRI Research, Policy, Innovation & Networks blog)
date: '2017-11-21'
slug: mvlri-blog-post-on-data-practices
categories: [publication]
tags: [data-science-ed]
description: Post on the practical impact of ongoing research with MVS and MVLRI
meta_img: /images/image.jpg
---

I have worked to design activities for students to work with authentic data sources in their science classes through a collaboration with [Michigan Virtual School](https://michiganvirtual.org) and the [Michigan Virtual Learning Research Institute](https://mvlri.org/). 

As a part of this project, which was supported by their dissertation research fellowship, I hosted a [webinar](https://jrosen48.github.io/blog/mvlri-webinar/). I also wrote a post for the Michigan Virtual Learning Research Institute Blog: Research, Policy, Innovation & Networks [blog](https://mvlri.org/blog).

Here is an excerpt of the post:

> Data are powerful, both in science and science education as well as in our everyday lives. By preparing students to think about data, students can question the claims of scientists, news media, and experts in marketing by questioning what data were collected – and how. Moreover, by preparing students to think with data, students can use data to answer questions that are relevant and interesting to them. Being able to think of and with data is powerful not only in science (and other STEM areas of study) but also in occupations that did not traditionally involve a focus on data, such as journalism.

> This post explores the topic of work with data, particularly a set of activities, or what the Next Generation Science Standards [1] (NGSS and the similar Michigan Science Standards) and the Common Core State Standards (CCSS) refer to as “practice.” In short, these are activities akin to what experts in STEM—scientists, mathematicians, engineers, and even data scientists—do. To refer to practices focused on work with data, we use the term “data practices.” Data practices draw not only from the practices of developing and using models and analyzing and interpreting data, but also obtaining, evaluating, and communicating information and, in many cases, using mathematics and computational thinking.

The post was published yesterday and I hope you check it (and the excellent posts by other scholars and administrators on the blog) [here](https://mvlri.org/blog/opportunities-engaging-students-data-practices-online-science-classes/).
