---
title: 'AERA 2018 presentation: How engagement during out-of-school STEM programs promotes the development of interest (slides, paper, & code)'
author: ''
date: '2018-04-14'
slug: aera-presentation-how-engagement-during-out-of-school-stem-programs-promotes-the-development-of-interest
categories: []
tags: []
description: Desc
meta_img: /images/image.jpg
---

I'm excited to present a paper on how engagement during out-of-school STEM programs promotes youths' development of interest with my co-authors Patrick Beymer and Jennifer Schmidt. 

The paper is in the session "Data-Intensive Approaches to Studying Engagement in Education: Exploring Their Current Potential". My co-presenters in the session include Eric Weibe and James Creager, Sophia Hooper, Erica Patall, Ariana Vasquez, Keenan Pituch, and Rebecca Steingut, and Eric Poitas, Tenzin Doleck, Lingyun Huang, Shan Li, & Susanne Lajoie. Ryan Baker is serving as the discussant.

If you are at AERA, the session is at 2:15 pm at the Millenium Broadway Hotel (Room 5.08). 

* [Slides here](/_media/slides/Rosenberg, Beymer, & Schmidt - 2018, AERA.pptx)
* [Paper here](/_media/publications/Rosenberg, Beymer, & Schmidt, 2018 - AERA.pdf)
* [Code here](https://github.com/jrosen48/mcmcglmm/blob/master/mcmgglmm-example-3.Rmd)
